assetManager.imageQueue = [
	{
		"type": "anim",
		"source": "gfx/player/walk.png",
		"frames": 8,
		"speed": 5,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 3,
		"loop": true,
		"offsetX": 7,
		"offsetY": 7,
		"flipOffsetX": 7,
		"hasFacing": true
	},
	{
		"type": "anim",
		"source": "gfx/player/walk_carry.png",
		"frames": 8,
		"speed": 5,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 3,
		"loop": true,
		"offsetX": 7,
		"offsetY": 7,
		"flipOffsetX": 7,
		"hasFacing": true
	},
	{
		"type": "anim",
		"source": "gfx/player/stand.png",
		"frames": 1,
		"speed": 3,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 1,
		"loop": false,
		"offsetX": 7,
		"offsetY": 7,
		"flipOffsetX": 7,
		"hasFacing": true
	},
	{
		"type": "anim",
		"source": "gfx/player/stand_carry.png",
		"frames": 1,
		"speed": 3,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 1,
		"loop": false,
		"offsetX": 7,
		"offsetY": 7,
		"flipOffsetX": 7,
		"hasFacing": true
	},
	{
		"type": "anim",
		"source": "gfx/player/jump.png",
		"frames": 3,
		"speed": 3,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 3,
		"loop": false,
		"offsetX": 7,
		"offsetY": 7,
		"flipOffsetX": 7,
		"hasFacing": true
	},
	{
		"type": "anim",
		"source": "gfx/player/jump_carry.png",
		"frames": 3,
		"speed": 3,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 3,
		"loop": false,
		"offsetX": 7,
		"offsetY": 7,
		"flipOffsetX": 7,
		"hasFacing": true
	},
	{
		"type": "anim",
		"source": "gfx/player/fall.png",
		"frames": 3,
		"speed": 3,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 3,
		"loop": false,
		"offsetX": 7,
		"offsetY": 7,
		"flipOffsetX": 7,
		"hasFacing": true
	},
	{
		"type": "anim",
		"source": "gfx/player/fall_carry.png",
		"frames": 3,
		"speed": 3,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 3,
		"loop": false,
		"offsetX": 7,
		"offsetY": 7,
		"flipOffsetX": 7,
		"hasFacing": true
	},
	{
		"type": "anim",
		"source": "gfx/misc/heart.png",
		"frames": 8,
		"speed": 3,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 4,
		"loop": true,
		"offsetX": 7,
		"offsetY": 7,
		"flipOffsetX": 7,
		"hasFacing": false 
	},
	{
		"type": "anim",
		"source": "gfx/misc/fire.png",
		"frames": 4,
		"speed": 6,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 2,
		"loop": true,
		"offsetX": 0,
		"offsetY": 0,
		"flipOffsetX": 0,
		"hasFacing": false 
	},
	{
		"type": "anim",
		"source": "gfx/misc/goal.png",
		"frames": 4,
		"speed": 6,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 2,
		"loop": true,
		"offsetX": 0,
		"offsetY": 0,
		"flipOffsetX": 0,
		"hasFacing": false 
	},
	{
		"type": "anim",
		"source": "gfx/misc/sparkle_particle.png",
		"frames": 9,
		"speed": 3,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 3,
		"loop": false,
		"offsetX": 16,
		"offsetY": 16,
		"flipOffsetX": 16,
		"hasFacing": false 
	},
	{
		"type": "anim",
		"source": "gfx/misc/grating_block.png",
		"frames": 1,
		"speed": 6,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 1,
		"loop": false,
		"offsetX": 0,
		"offsetY": 0,
		"flipOffsetX": 0,
		"hasFacing": false 
	},
	{
		"type": "anim",
		"source": "gfx/misc/destroyable_block.png",
		"frames": 1,
		"speed": 6,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 1,
		"loop": false,
		"offsetX": 0,
		"offsetY": 0,
		"flipOffsetX": 0,
		"hasFacing": false 
	},
	{
		"type": "anim",
		"source": "gfx/misc/flare_particle.png",
		"frames": 6,
		"speed": 4,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 3,
		"loop": true,
		"offsetX": 16,
		"offsetY": 16,
		"flipOffsetX": 16,
		"hasFacing": false 
	},
	{
		"type": "anim",
		"source": "gfx/misc/smoke_particle.png",
		"frames": 6,
		"speed": 6,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 3,
		"loop": false,
		"offsetX": 16,
		"offsetY": 16,
		"flipOffsetX": 16,
		"hasFacing": false 
	},
	{
		"type": "anim",
		"source": "gfx/misc/breakable_particle.png",
		"frames": 1,
		"speed": 4,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 3,
		"loop": false,
		"offsetX": 16,
		"offsetY": 16,
		"flipOffsetX": 16,
		"hasFacing": false 
	},
	{
		"type": "anim",
		"source": "gfx/misc/fan_off.png",
		"frames": 1,
		"speed": 4,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 1,
		"loop": false,
		"offsetX": 0,
		"offsetY": 0,
		"flipOffsetX": 0,
		"hasFacing": false 
	},
	{
		"type": "anim",
		"source": "gfx/misc/fan_on.png",
		"frames": 3,
		"speed": 4,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 3,
		"loop": true,
		"offsetX": 0,
		"offsetY": 0,
		"flipOffsetX": 0,
		"hasFacing": false 
	},
	{
		"type": "anim",
		"source": "gfx/misc/door.png",
		"frames": 6,
		"speed": 4,
		"frameWidth": 32,
		"frameHeight": 32,
		"numCols": 3,
		"loop": false,
		"offsetX": 0,
		"offsetY": 0,
		"flipOffsetX": 0,
		"hasFacing": false 
	},


	//TILESETS BELOW
	{
		"type": "tileset",
		"source": "gfx/tilesets/foreground.png",
		"width": 16,
		"height": 16
	},
	{
		"type": "tileset",
		"source": "gfx/tilesets/background.png",
		"width": 16,
		"height": 16 
	}



];
